import { Plan } from "./types";

export const plans: Plan[] = [
  {
    id: "free",
    name: "FREE PLAN",
    price: {
      monthly: 0,
      annually: 0,
    },
    description: "Start with the basics",
    features: {
      webinars: "Not Included",
      personalProfiles: 1,
      entityProfiles: "N/A",
      assetsCreation: "N/A",
      sellingProducts: "N/A",
      buyingProducts: "Unlimited",
      profilesEngagement: "Unlimited",
      creditsRedemption: "Yes",
      creditsValue: "$1",
      storageSpace: "1 GB",
    },
  },
  {
    id: "silver",
    name: "SILVER PLAN",
    price: {
      monthly: 30,
      annually: 24,
    },
    description: "Perfect for small businesses",
    features: {
      webinars: "Include V-Webi",
      personalProfiles: 1,
      entityProfiles: 1,
      assetsCreation: "Yes",
      sellingProducts: "Yes",
      buyingProducts: "Unlimited",
      profilesEngagement: "Unlimited",
      creditsRedemption: "Yes",
      creditsValue: "$1",
      storageSpace: "2 GB",
    },
  },
  {
    id: "gold",
    name: "GOLD PLAN",
    price: {
      monthly: 50,
      annually: 40,
    },
    description: "Best for growing teams",
    features: {
      webinars: "Include V-Web",
      personalProfiles: 1,
      entityProfiles: 3,
      assetsCreation: "Yes",
      sellingProducts: "Yes",
      buyingProducts: "Unlimited",
      profilesEngagement: "Unlimited",
      creditsRedemption: "Yes",
      creditsValue: "$1",
      storageSpace: "5 GB",
    },
    isPopular: true,
  },
  {
    id: "platinum",
    name: "PLATINUM PLAN",
    price: {
      monthly: 400,
      annually: 320,
    },
    description: "For large enterprises",
    features: {
      webinars: "Include V-Webin",
      personalProfiles: 1,
      entityProfiles: 5,
      assetsCreation: "Yes",
      sellingProducts: "Yes",
      buyingProducts: "Unlimited",
      profilesEngagement: "Unlimited",
      creditsRedemption: "Yes",
      creditsValue: "$1",
      storageSpace: "10 GB",
    },
  },
];
